# Generated by Django 5.2.3 on 2026-01-06 05:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raza')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Especie')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('age_years', models.IntegerField(help_text='Edad aproximada en años', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Edad (años)')),
                ('age_months', models.IntegerField(default=0, help_text='Meses adicionales (0-11)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Meses adicionales')),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('size', models.CharField(choices=[('small', 'Pequeño (0-10 kg)'), ('medium', 'Mediano (11-25 kg)'), ('large', 'Grande (26-45 kg)'), ('xlarge', 'Extra Grande (45+ kg)')], max_length=10, verbose_name='Tamaño')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('description', models.TextField(verbose_name='Descripción general')),
                ('health_status', models.CharField(choices=[('healthy', 'Saludable'), ('treatment', 'En Tratamiento')], default='healthy', max_length=20, verbose_name='Estado de salud')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vacunado')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('dewormed', models.BooleanField(default=False, verbose_name='Desparasitado')),
                ('microchipped', models.BooleanField(default=False, verbose_name='Con microchip')),
                ('good_with_kids', models.BooleanField(default=True, verbose_name='Bueno con niños')),
                ('good_with_dogs', models.BooleanField(default=True, verbose_name='Bueno con perros')),
                ('good_with_cats', models.BooleanField(default=True, verbose_name='Bueno con gatos')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('pending', 'Adopción Pendiente'), ('adopted', 'Adoptado'), ('unavailable', 'No Disponible')], default='available', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.breed', verbose_name='Raza')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.species', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/%Y/%m/%d/', verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Imagen de Mascota',
                'verbose_name_plural': 'Imágenes de Mascotas',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pets.species', verbose_name='Especie'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status', '-created_at'], name='pets_pet_status_a8f086_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species', 'status'], name='pets_pet_species_38ca25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
    ]
