# Generated by Django 5.2.10 on 2026-01-27 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_lost_report',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='reported_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PetFaceDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('descriptor', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_descriptors', to='pets.pet')),
                ('pet_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_descriptors', to='pets.petimage')),
            ],
            options={
                'indexes': [models.Index(fields=['pet'], name='pets_petfac_pet_id_daf9f9_idx')],
            },
        ),
    ]
