# Generated by Django 5.2.10 on 2026-01-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_is_lost_report_pet_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='ubication_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
