# Generated by Django 5.2.10 on 2026-01-29 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_ubication_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_months',
            field=models.IntegerField(blank=True, default=0, help_text='Meses adicionales (0-11)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Meses adicionales'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_years',
            field=models.IntegerField(blank=True, help_text='Edad aproximada en años', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Edad (años)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
