# Generated by Django 5.2.10 on 2026-01-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_age_months_alter_pet_age_years_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='petfacedescriptor',
            name='pets_petfac_pet_id_daf9f9_idx',
        ),
        migrations.AddField(
            model_name='petfacedescriptor',
            name='descriptor_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petfacedescriptor',
            name='algorithm',
            field=models.CharField(choices=[('arcface', 'ArcFace Embedding'), ('resnet50', 'ResNet50 Embedding'), ('sift', 'SIFT Descriptors'), ('orb', 'ORB Descriptors'), ('yolo_face', 'YOLO Pet Face Detection')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='petfacedescriptor',
            index=models.Index(fields=['pet', 'algorithm'], name='pets_petfac_pet_id_a5bd81_idx'),
        ),
        migrations.AddIndex(
            model_name='petfacedescriptor',
            index=models.Index(fields=['algorithm', 'created_at'], name='pets_petfac_algorit_e37be5_idx'),
        ),
    ]
