# Generated by Django 5.2.10 on 2026-02-04 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_petfacedescriptor_pets_petfac_pet_id_daf9f9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('pending', 'Adopción Pendiente'), ('adopted', 'Adoptado'), ('unavailable', 'No Disponible'), ('lost', 'Perdido'), ('found', 'Encontrado')], default='available', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='0-100, donde 100 es idéntico', verbose_name='Porcentaje de Similitud')),
                ('algorithm', models.CharField(max_length=50, verbose_name='Algoritmo Usado')),
                ('match_details', models.JSONField(default=dict, help_text='Información adicional sobre la coincidencia', verbose_name='Detalles del Match')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Revisión'), ('confirmed', 'Confirmado - Es la misma mascota'), ('rejected', 'Rechazado - No es la misma'), ('contacted', 'Usuario contactado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('found_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_as_found', to='pets.pet', verbose_name='Posible Coincidencia')),
                ('lost_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to='pets.pet', verbose_name='Mascota Perdida')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Coincidencia de Mascota',
                'verbose_name_plural': 'Coincidencias de Mascotas',
                'ordering': ['-similarity_score', '-created_at'],
                'indexes': [models.Index(fields=['lost_pet', 'status'], name='pets_petmat_lost_pe_01bbd0_idx'), models.Index(fields=['similarity_score', '-created_at'], name='pets_petmat_similar_648819_idx')],
                'unique_together': {('lost_pet', 'found_pet')},
            },
        ),
    ]
